# RULE (filepicker)
windowrulev2 = tag +filepicker, title:(Open Files)
windowrulev2 = float, tag:filepicker
windowrulev2 = size 1000 600, tag:filepicker

# RULES (savefile)
windowrulev2 = tag +savefileapplet, title:(Save File)
windowrulev2 = float, tag:savefileapplet
windowrulev2 = size 1000 600, tag:savefileapplet
