# GENERAL
general {
  disable_loading_bar = true
  hide_cursor = true
}


# BACKGROUND
background {
    monitor =
    path = $HOME/.config/hypr/assets/images/hyprlock-bg.jpg
    blur_size = 10
    blur_passes = 1
    noise = 0.0117
    contrast = 1.3000
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

# IMAGE::AVATAR
image {
  monitor =
  path = $HOME/.config/hypr/assets/images/shyamin-md.jpg
  size = 150
  border_size = 10
  position = 0, 75
  halign = center
  valign = center
}