#!/bin/bash

branch_name=$(git symbolic-ref -q HEAD)
branch_name=${branch_name##refs/heads/}
branch_name=${branch_name:-HEAD}

git checkout prod
git merge $branch_name
git checkout $branch_name
git push -u origin --all
