name: AUR
on:
  push:
  workflow_dispatch:


jobs:

  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: git::tag::get
      #   id: tag
      #   uses: actions-ecosystem/action-get-latest-tag@v1

      - name: pkgbuild::sha256sums
        run: |
          sed -i 's/sha256sums=("f2f55de04b08a767eaa1f2c50a797606f8b21f4c5de5334e314530cd521f8954")/sha256sums=("test")/g' PKGBUILD
          cat PKGBUILD

      # - name: Debug
      #   run: echo ${{ steps.tag.outputs.tag }}
